---
name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_ggb:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Testing across Linux and macOS
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libc++-dev libc++abi-dev

      - name: Build GGB
        shell: bash
        run: |
          ./scripts/ggb_build.sh ${{ matrix.build_type }}

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Testing across Linux and macOS
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libc++-dev libc++abi-dev

      - name: Run GGB Tests
        shell: bash
        run: |
          ./scripts/ggb_run_tests.sh

  build_bench:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Testing across Linux and macOS
        os: [ubuntu-latest, macos-latest]
        build_type: [Release]

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libc++-dev libc++abi-dev

      - name: Build GGB Benchmarks
        shell: bash
        run: |
          ./scripts/ggb_build.sh ${{ matrix.build_type }}

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version-file: "bench/query_gen/.python-version"

      - name: Install uv
        shell: bash
        run: curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh

      - name: Build Benchmarks Python Env
        shell: bash
        run: |
          ./scripts/bench_setup_python.sh
