---
name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_ggb:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Testing across Linux and macOS
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libc++-dev libc++abi-dev

      - name: Build GGB
        shell: bash
        run: |
          ./scripts/ggb_build.sh ${{ matrix.build_type }}

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Testing across Linux and macOS
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libc++-dev libc++abi-dev

      - name: Run GGB Tests
        shell: bash
        run: |
          ./scripts/ggb_run_tests.sh

  build_bench:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Testing across Linux and macOS
        os: [ubuntu-latest, macos-latest]
        build_type: [Release]

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libc++-dev libc++abi-dev

      - name: Build GGB Benchmarks
        shell: bash
        run: |
          ./scripts/ggb_build.sh ${{ matrix.build_type }} --bench

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install $(cat bench/query_gen/.python-version)

      - name: Build Benchmarks Python Env
        shell: bash
        run: |
          ./scripts/bench_setup_python.sh

  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install $(cat bench/query_gen/.python-version)

      - name: "Run Ruff Linting"
        uses: astral-sh/ruff-action@v1
        with:
          changed-files: "true"

  python-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install $(cat bench/query_gen/.python-version)

      - name: "Run Ruff Formatter"
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
          version-file: "bench/query_gen/pyproject.toml"

  python-static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install $(cat bench/query_gen/.python-version)

      - name: "Run Mypy"
        run: uv run --with mypy mypy bench/query_gen --ignore-missing-imports

  cpp-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Clang Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libc++-dev libc++abi-dev

      - name: Build GGB Benchmarks (for compilation db)
        shell: bash
        run: |
          ./scripts/ggb_build.sh ${{ matrix.build_type }} --bench

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          database: "build"
          style: "file" # Use .clang-format config file
          tidy-checks: "" # Use .clang-tidy config file
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
